
import { SculpturePark } from './types';

export const INITIAL_PARKS: SculpturePark[] = [
  // --- SCANDINAVIË ---
  { id: 'scan-01', name: 'Deep Forest Art Land', location: 'Kibæk', region: 'Denemarken', lat: 55.9193, lng: 8.9074, website: '#', shortDescription: 'Skovsnogen Landart: Een experimentele buitenexpositie in het Deense bos.' },
  { id: 'scan-02', name: 'TICKON', location: 'Langeland', region: 'Denemarken', lat: 55.0003, lng: 10.8444, website: '#', shortDescription: 'Tranekær Slotspark: Internationale land-art in een historisch kasteelpark.' },
  { id: 'scan-03', name: 'Wanås Konst', location: 'Knislinge', region: 'Zweden', lat: 56.1852, lng: 14.0444, website: '#', shortDescription: 'Beeldenbos Skåne: Een wereldberoemd park met meer dan 70 permanente installaties.' },
  { id: 'scan-04', name: 'Kistefos Sculpture Park', location: 'Jevnaker', region: 'Noorwegen', lat: 60.2227, lng: 10.3705, website: '#', shortDescription: 'The Twist & Park: Spectaculair museum en beeldenpark aan de rivier.' },
  { id: 'scan-05', name: 'Ekebergparken', location: 'Oslo', region: 'Noorwegen', lat: 59.8944, lng: 10.7611, website: '#', shortDescription: 'Landart & Beeldenpark met uitzicht over de Oslofjord.' },
  { id: 'scan-06', name: 'Vigelandparken', location: 'Oslo', region: 'Noorwegen', lat: 59.9270, lng: 10.7008, website: '#', shortDescription: 'Grootste beeldenpark ter wereld door één kunstenaar.' },
  { id: 'scan-07', name: 'Umedalen Skulpturpark', location: 'Umeå', region: 'Zweden', lat: 63.8392, lng: 20.1664, website: '#', shortDescription: 'Openluchtkunst in een voormalig ziekenhuisterrein.' },
  { id: 'scan-08', name: 'Louisiana Sculpture Park', location: 'Humlebæk', region: 'Denemarken', lat: 55.9691, lng: 12.5431, website: '#', shortDescription: 'Kustpark Museum: Sculpturen van wereldklasse aan de Sont.' },
  { id: 'scan-09', name: 'Bærums Verk', location: 'Bærum', region: 'Noorwegen', lat: 59.9392, lng: 10.5036, website: '#', shortDescription: 'Sculptuurpark langs de rivier in een historisch ijzerwerk.' },
  { id: 'scan-10', name: 'Millesgården', location: 'Stockholm', region: 'Zweden', lat: 59.3589, lng: 18.1214, website: '#', shortDescription: 'Terrassen & Beelden: Het huis en de tuinen van Carl Milles.' },
  { id: 'scan-11', name: 'Dronningens Skulpturpark', location: 'Oslo', region: 'Noorwegen', lat: 59.9169, lng: 10.7275, website: '#', shortDescription: 'Paleistuinen met beelden speciaal voor kinderen.' },
  { id: 'scan-12', name: 'Arken Museum Park', location: 'Ishøj', region: 'Denemarken', lat: 55.6062, lng: 12.3861, website: '#', shortDescription: 'Kustsculpturen rondom het Arken Museum.' },
  { id: 'scan-13', name: 'Havmannen (Nordland)', location: 'Mo i Rana', region: 'Noorwegen', lat: 66.3121, lng: 14.1378, website: '#', shortDescription: 'Imposant beeld in het water van de fjord.' },
  { id: 'scan-14', name: 'Steinar the Monkfish', location: 'Brønnøysund', region: 'Noorwegen', lat: 65.4741, lng: 12.2125, website: '#', shortDescription: 'Grote sculptuur langs de ruige kust.' },
  { id: 'scan-15', name: 'The Nest (Reiret)', location: 'Røst', region: 'Noorwegen', lat: 67.4833, lng: 12.0167, website: '#', shortDescription: 'Vogeleiland Vedøy: Landart installatie.' },
  { id: 'scan-16', name: 'Haiku Bathtub', location: 'Sømna', region: 'Noorwegen', lat: 65.2117, lng: 12.0461, website: '#', shortDescription: 'Poëtische kustlocatie met sculptuur.' },
  { id: 'scan-17', name: 'The Head (Hodet)', location: 'Lofoten', region: 'Noorwegen', lat: 68.2167, lng: 13.6833, website: '#', shortDescription: 'Kust Vestvågøy: Kunst die van perspectief verandert.' },
  { id: 'scan-18', name: 'House of Winds', location: 'Alstahaug', region: 'Noorwegen', lat: 65.9861, lng: 12.6361, website: '#', shortDescription: 'Nabij Helgelandbrug: Monumentaal werk.' },
  { id: 'scan-19', name: 'A New Conversation', location: 'Vega', region: 'Noorwegen', lat: 65.6755, lng: 11.9567, website: '#', shortDescription: 'Kustlijn Vega: Onderdeel van de Skulpturlandskap Nordland.' },
  { id: 'scan-20', name: 'Varde (Per Kirkeby)', location: 'Meløy', region: 'Noorwegen', lat: 66.7161, lng: 13.5667, website: '#', shortDescription: 'Brevikhøyden: Bakstenen sculptuur van de Deense meester.' },
  { id: 'scan-21', name: 'The Mirror (Graham)', location: 'Vågan', region: 'Noorwegen', lat: 68.2341, lng: 14.5667, website: '#', shortDescription: 'Uitzichtpunt met spiegelende installatie.' },
  { id: 'scan-22', name: 'Stone House', location: 'Evenes', region: 'Noorwegen', lat: 68.5122, lng: 16.6855, website: '#', shortDescription: 'Langs de weg: Sculptuur van natuursteen.' },
  { id: 'scan-23', name: 'Seven Magic Points', location: 'Skjerstad', region: 'Noorwegen', lat: 67.2345, lng: 15.0234, website: '#', shortDescription: 'Natuurreservaat: Sculptuur in dialoog met de wildernis.' },
  { id: 'scan-24', name: 'Altar in the Woods', location: 'Kibæk', region: 'Denemarken', lat: 55.9205, lng: 8.9085, website: '#', shortDescription: 'Deep Forest Art Land installatie.' },
  { id: 'scan-25', name: 'Fallen Moon', location: 'Kibæk', region: 'Denemarken', lat: 55.9201, lng: 8.9082, website: '#', shortDescription: 'Landart installatie in het Deense bos.' },
  { id: 'scan-26', name: 'Nimis (Lars Vilks)', location: 'Kullaberg', region: 'Zweden', lat: 56.2811, lng: 12.5383, website: '#', shortDescription: 'Drijfhoutsculptuur aan de Zweedse kust.' },
  { id: 'scan-27', name: 'Ararat (Lars Vilks)', location: 'Kullaberg', region: 'Zweden', lat: 56.2815, lng: 12.5388, website: '#', shortDescription: 'Drijfhoutsculptuur nabij Nimis.' },
  { id: 'scan-28', name: 'Oscar under the Bridge', location: 'Ishøj', region: 'Denemarken', lat: 55.6065, lng: 12.3850, website: '#', shortDescription: 'Forgotten Giant van Thomas Dambo.' },
  { id: 'scan-29', name: 'Little Tilde', location: 'Vallensbæk', region: 'Denemarken', lat: 55.6322, lng: 12.3855, website: '#', shortDescription: 'Forgotten Giant in de natuur bij Kopenhagen.' },
  { id: 'scan-30', name: 'Teddy Friendly', location: 'Taastrup', region: 'Denemarken', lat: 55.6569, lng: 12.2471, website: '#', shortDescription: 'Forgotten Giant van gerecycled hout.' },
  { id: 'scan-31', name: 'Thomas on Mountain', location: 'Taastrup', region: 'Denemarken', lat: 55.6417, lng: 12.2831, website: '#', shortDescription: 'Forgotten Giant met uitzicht over het landschap.' },
  { id: 'scan-32', name: 'Sleeping Louis', location: 'Rødovre', region: 'Denemarken', lat: 55.6781, lng: 12.4332, website: '#', shortDescription: 'Forgotten Giant verscholen in het groen.' },
  { id: 'scan-33', name: 'Hill of the Sun', location: 'Langeland', region: 'Denemarken', lat: 55.0003, lng: 10.8444, website: '#', shortDescription: 'Tranekær Park: Landart monument.' },
  { id: 'scan-34', name: 'Forest Tower', location: 'Rønnede', region: 'Denemarken', lat: 55.2533, lng: 11.9806, website: '#', shortDescription: 'Camp Adventure: Iconische houten toren.' },
  { id: 'scan-35', name: 'Broken Column (1)', location: 'Stavanger', region: 'Noorwegen', lat: 58.9535, lng: 5.7198, website: '#', shortDescription: 'Antony Gormley project in Stavanger.' },
  { id: 'scan-36', name: 'Broken Column (2)', location: 'Stavanger', region: 'Noorwegen', lat: 58.9699, lng: 5.7331, website: '#', shortDescription: 'Gormley beelden verspreid door de stad.' },
  { id: 'scan-37', name: 'Kulturen i Lund', location: 'Lund', region: 'Zweden', lat: 55.7050, lng: 13.1964, website: '#', shortDescription: 'Openluchtmuseum met historische architectuur en kunst.' },
  { id: 'scan-38', name: 'Moderna Museet Park', location: 'Stockholm', region: 'Zweden', lat: 59.3261, lng: 18.0847, website: '#', shortDescription: 'Skeppsholmen: Sculpturen van o.a. Picasso en Calder.' },
  { id: 'scan-39', name: 'Marabouparken', location: 'Sundbyberg', region: 'Zweden', lat: 59.3625, lng: 17.9625, website: '#', shortDescription: 'Bekroond beeldenpark en kunsthal.' },
  { id: 'scan-40', name: 'Guldagergaard Park', location: 'Skælskør', region: 'Denemarken', lat: 55.2558, lng: 11.2917, website: '#', shortDescription: 'Internationaal keramisch beeldenpark.' },

  // --- DUITSLAND ---
  { id: 'de-01', name: 'Waldskulpturenweg (Start West)', location: 'Bad Berleburg', region: 'Duitsland', lat: 51.0543, lng: 8.3551, website: '#', shortDescription: 'Uitzichtpunt & kunstroute in het Sauerland.' },
  { id: 'de-02', name: 'Waldskulpturenweg (Start Oost)', location: 'Schmallenberg', region: 'Duitsland', lat: 51.1378, lng: 8.3842, website: '#', shortDescription: 'Uitzichtpunt & kunstroute aan de oostzijde.' },
  { id: 'de-03', name: 'Skulpturenpark Waldfrieden', location: 'Wuppertal', region: 'Duitsland', lat: 51.2522, lng: 7.1685, website: '#', shortDescription: 'Tony Cragg Foundation: Topcollectie in bospark.' },
  { id: 'de-04', name: 'Skulpturenpark Köln', location: 'Keulen', region: 'Duitsland', lat: 50.9521, lng: 6.9719, website: '#', shortDescription: 'Openluchtmuseum voor moderne sculptuur nabij de Rijn.' },
  { id: 'de-05', name: 'Kunstwanderweg Hoher Fläming', location: 'Wiesenburg', region: 'Duitsland', lat: 52.1128, lng: 12.4542, website: '#', shortDescription: 'Route door natuurpark met verrassende kunst.' },
  { id: 'de-06', name: 'Emscherkunst (Landschaftspark)', location: 'Duisburg', region: 'Duitsland', lat: 51.4688, lng: 6.7658, website: '#', shortDescription: 'Industrieel erfgoed en grootschalige installaties.' },
  { id: 'de-07', name: 'Stiftung Insel Hombroich', location: 'Neuss', region: 'Duitsland', lat: 51.1472, lng: 6.6583, website: '#', shortDescription: 'Kunst/Natuur landschap: Uniek museumconcept.' },
  { id: 'de-08', name: 'Internationales Waldkunstzentrum', location: 'Darmstadt', region: 'Duitsland', lat: 49.8514, lng: 8.6656, website: '#', shortDescription: 'Darmstädter Wald: Landart langs bospaden.' },
  { id: 'de-09', name: 'Skulpturenufer Remagen', location: 'Remagen', region: 'Duitsland', lat: 50.5786, lng: 7.2283, website: '#', shortDescription: 'Openluchtgalerie langs de oevers van de Rijn.' },
  { id: 'de-10', name: 'Bernrieder Park', location: 'Bernried', region: 'Duitsland', lat: 47.8653, lng: 11.2958, website: '#', shortDescription: 'Beelden aan de Starnberger See in Beieren.' },
  { id: 'de-11', name: 'Kunstpfad Bonstetten', location: 'Bonstetten', region: 'Duitsland', lat: 48.4384, lng: 10.7061, website: '#', shortDescription: 'Interactieve kunstroute door het bos.' },
  { id: 'de-12', name: 'Skulpturenlandschaft Prignitz', location: 'Prignitz', region: 'Duitsland', lat: 53.2201, lng: 12.0412, website: '#', shortDescription: 'Kunst in een weids Brandenburgs landschap.' },
  { id: 'de-13', name: 'Skulpturenpark Durbach', location: 'Durbach', region: 'Duitsland', lat: 48.4901, lng: 8.0125, website: '#', shortDescription: 'Sculpturen nabij Museum Hurrle in het Zwarte Woud.' },
  { id: 'de-14', name: 'Skulpturenweg Winnenden', location: 'Winnenden', region: 'Duitsland', lat: 48.8767, lng: 9.3975, website: '#', shortDescription: 'Kunstroute langs de beek de Buchenbach.' },
  { id: 'de-15', name: 'Skulpturenpark Mannheim', location: 'Mannheim', region: 'Duitsland', lat: 49.4975, lng: 8.4791, website: '#', shortDescription: 'Beeldenpark nabij de Kunsthalle Mannheim.' },
  { id: 'de-16', name: 'Opelvillen Skulpturenpark', location: 'Rüsselsheim', region: 'Duitsland', lat: 49.9911, lng: 8.4069, website: '#', shortDescription: 'Museumstuin met focus op moderne beelden.' },
  { id: 'de-17', name: 'Klutes Land-Art', location: 'Schmallenberg', region: 'Duitsland', lat: 51.1578, lng: 8.2811, website: '#', shortDescription: 'Galerie en kunstprojecten in de vrije natuur.' },
  { id: 'de-18', name: 'Klosterpark Seligenthal', location: 'Landshut', region: 'Duitsland', lat: 48.5422, lng: 12.1643, website: '#', shortDescription: 'Sculpturen in een serene kloostertuin.' },
  { id: 'de-19', name: 'Kunst in der Flur', location: 'Müncheberg', region: 'Duitsland', lat: 52.5204, lng: 14.1205, website: '#', shortDescription: 'Landart project in het oosten van Duitsland.' },
  { id: 'de-20', name: 'Euro Land Art Hester Pilz', location: 'Straelen', region: 'Duitsland', lat: 51.4880, lng: 6.2340, website: '#', shortDescription: 'Grieselveld: Grensoverschrijdend kunstproject.' },
  { id: 'de-21', name: 'Landart Wadden Sea', location: 'Büsum', region: 'Duitsland', lat: 54.1232, lng: 8.8710, website: '#', shortDescription: 'Tijdelijke werken in het Werelderfgoed Waddenzee.' },
  { id: 'de-22', name: 'Gärten der Welt', location: 'Berlijn', region: 'Duitsland', lat: 52.5050, lng: 13.6264, website: '#', shortDescription: 'Internationale tuinkunst en beelden in Marzahn.' },
  { id: 'de-23', name: 'East Side Gallery', location: 'Berlijn', region: 'Duitsland', lat: 52.5020, lng: 13.4446, website: '#', shortDescription: 'Beroemde muurschilderingen op de Berlijnse Muur.' },
  { id: 'de-24', name: 'URBAN NATION Museum', location: 'Berlijn', region: 'Duitsland', lat: 52.4920, lng: 13.3644, website: '#', shortDescription: 'Urban Art en muurschilderingen in Schöneberg.' },
  { id: 'de-25', name: 'Kiefernstrasse Community', location: 'Düsseldorf', region: 'Duitsland', lat: 51.2110, lng: 6.8045, website: '#', shortDescription: 'Iconische Street Art straat.' },
  { id: 'de-26', name: 'Walls of Wonder (Ehrenfeld)', location: 'Keulen', region: 'Duitsland', lat: 50.9490, lng: 6.9310, website: '#', shortDescription: 'Street Art route door de wijk Ehrenfeld.' },
  { id: 'de-27', name: 'Teufelsberg', location: 'Berlijn', region: 'Duitsland', lat: 52.5014, lng: 13.2384, website: '#', shortDescription: 'Street Art en historisch luisterstation.' },

  // --- NEDERLAND ---
  { id: 'nl-01', name: 'Observatorium (Robert Morris)', location: 'Lelystad', region: 'Nederland', lat: 52.5511, lng: 5.5564, website: '#', shortDescription: 'Land Art project nabij de Houtribweg.' },
  { id: 'nl-02', name: 'Aardzee (Piet Slegers)', location: 'Zeewolde', region: 'Nederland', lat: 52.3486, lng: 5.4372, website: '#', shortDescription: 'Vogelweg: Een golvend polderlandschap.' },
  { id: 'nl-03', name: 'Sea Level (Richard Serra)', location: 'Zeewolde', region: 'Nederland', lat: 52.3333, lng: 5.5342, website: '#', shortDescription: 'Weteringpark: Betonmuren die de zeespiegel verbeelden.' },
  { id: 'nl-04', name: 'De Groene Kathedraal', location: 'Almere', region: 'Nederland', lat: 52.3217, lng: 5.3200, website: '#', shortDescription: 'Levend kunstwerk van populieren.' },
  { id: 'nl-05', name: 'Polderland Garden of Love and Fire', location: 'Almere', region: 'Nederland', lat: 52.4042, lng: 5.2508, website: '#', shortDescription: 'Daniel Libeskind landart project.' },
  { id: 'nl-06', name: 'Exposure (De Hurkende Man)', location: 'Lelystad', region: 'Nederland', lat: 52.5256, lng: 5.4361, website: '#', shortDescription: 'Antony Gormley sculptuur op de dijk.' },
  { id: 'nl-07', name: 'Pier+Horizon (Paul de Kort)', location: 'Noordoostpolder', region: 'Nederland', lat: 52.6105, lng: 5.9220, website: '#', shortDescription: 'Zwarte Meer: Drijvend kunstwerk.' },
  { id: 'nl-08', name: 'Deltawerk // (RAAAF)', location: 'Marknesse', region: 'Nederland', lat: 52.6681, lng: 5.9189, website: '#', shortDescription: 'Waterloopbos: Herbestemming van een proefopstelling.' },
  { id: 'nl-09', name: 'Riff PD#18245 (Bob Gramsma)', location: 'Dronten', region: 'Nederland', lat: 52.4339, lng: 5.7744, website: '#', shortDescription: 'Spijkweg: Monumentale afdruk in het landschap.' },
  { id: 'nl-10', name: 'Engelenstoot (Moniek Toebosch)', location: 'Enkhuizen-Lelystad', region: 'Nederland', lat: 52.6111, lng: 5.4167, website: '#', shortDescription: 'Houtribdijk: Geluidskunstwerk bij de sluizen.' },
  { id: 'nl-11', name: 'Land Art Park Buitenschot', location: 'Haarlemmermeer', region: 'Nederland', lat: 52.3275, lng: 4.7214, website: '#', shortDescription: 'Geluidsabsorberend park bij Schiphol.' },
  { id: 'nl-12', name: 'Beeldenpark Kröller-Müller', location: 'Otterlo', region: 'Nederland', lat: 52.0951, lng: 5.8197, website: '#', shortDescription: 'Hoge Veluwe: Een van Europa\'s grootste beeldentuinen.' },
  { id: 'nl-13', name: 'Museum Voorlinden (Tuinen)', location: 'Wassenaar', region: 'Nederland', lat: 52.1189, lng: 4.3314, website: '#', shortDescription: 'Piet Oudolf tuinen en moderne beelden.' },
  { id: 'nl-14', name: 'Sonsbeek Park', location: 'Arnhem', region: 'Nederland', lat: 51.9897, lng: 5.8986, website: '#', shortDescription: 'Historisch park met landart en sculptuur.' },
  { id: 'nl-15', name: 'Beelden aan Zee (Sprookjesbeelden)', location: 'Scheveningen', region: 'Nederland', lat: 52.1114, lng: 4.2811, website: '#', shortDescription: 'Iconische beelden op de boulevard.' },
  { id: 'nl-16', name: 'Landgoed Anningahof', location: 'Zwolle', region: 'Nederland', lat: 52.5264, lng: 6.1558, website: '#', shortDescription: 'Beeldenpark met jaarlijkse nieuwe exposities.' },
  { id: 'nl-17', name: 'Kasteel het Nijenhuis (Tuin)', location: 'Heino', region: 'Nederland', lat: 52.3992, lng: 6.2372, website: '#', shortDescription: 'Beeldentuin van Museum de Fundatie.' },
  { id: 'nl-18', name: 'Teylers Stichting (Buitenkunst)', location: 'Haarlem', region: 'Nederland', lat: 52.3808, lng: 4.6406, website: '#', shortDescription: 'Natuurgebied met geselecteerde buitenkunst.' },
  { id: 'nl-19', name: 'Kirchner-Park', location: 'Stichtse Vecht', region: 'Nederland', lat: 52.1583, lng: 5.0417, website: '#', shortDescription: 'Natuur en sculptuur langs de Vecht.' },
  { id: 'nl-20', name: 'De Nollen (Rudi van de Wint)', location: 'Den Helder', region: 'Nederland', lat: 52.9367, lng: 4.7761, website: '#', shortDescription: 'Totaalproject in het duingebied.' },
  { id: 'nl-21', name: 'Buitenplaats Doornburgh', location: 'Maarssen', region: 'Nederland', lat: 52.1467, lng: 5.0331, website: '#', shortDescription: 'Kunst en natuur route op een historisch landgoed.' },
  { id: 'nl-22', name: 'Park de Oude Warande', location: 'Tilburg', region: 'Nederland', lat: 51.5647, lng: 5.0347, website: '#', shortDescription: 'Lustwarande: Hedendaagse sculptuur exposities.' },
  { id: 'nl-23', name: 'Zeven continenten (Winiarski)', location: 'Amersfoort', region: 'Nederland', lat: 52.1561, lng: 5.3878, website: '#', shortDescription: 'Stalen sculpturen in het water.' },

  // --- BELGIË & LUXEMBURG ---
  { id: 'be-01', name: 'Middelheimmuseum', location: 'Antwerpen', region: 'België', lat: 51.1821, lng: 4.4150, website: '#', shortDescription: 'Groot openluchtmuseum met internationale topcollectie.' },
  { id: 'be-02', name: 'Fondation Verbeke', location: 'Kemzeke', region: 'België', lat: 51.2183, lng: 4.0628, website: '#', shortDescription: 'Anarchistische landart en ecologische kunst.' },
  { id: 'be-03', name: 'Beaufort Beeldenpark', location: 'Vlaamse Kust', region: 'België', lat: 51.2333, lng: 2.9167, website: '#', shortDescription: 'Permanente kunstwerken verspreid over de kust.' },
  { id: 'be-04', name: 'Klankenbos', location: 'Neerpelt', region: 'België', lat: 51.2294, lng: 5.4328, website: '#', shortDescription: 'Audiovisuele landart in een bosrijke omgeving.' },
  { id: 'be-05', name: 'Labiomista (Koen Vanmechelen)', location: 'Genk', region: 'België', lat: 51.0028, lng: 5.5264, website: '#', shortDescription: 'Kunst en biodiversiteit op een voormalige mijnsite.' },
  { id: 'be-06', name: 'Centre d\'Art Contemporain (CACLB)', location: 'Buzenol', region: 'België', lat: 49.6300, lng: 5.5900, website: '#', shortDescription: 'Boslocatie Montauban met site-specific kunst.' },
  { id: 'be-07', name: 'Art et Sénescence', location: 'Houffalize', region: 'België', lat: 50.1333, lng: 5.7833, website: '#', shortDescription: 'Landart route in een Ardens park.' },
  { id: 'be-08', name: 'Sculpturenterras (KMSKA)', location: 'Antwerpen', region: 'België', lat: 51.2086, lng: 4.3949, website: '#', shortDescription: 'Museumtuin met moderne sculpturen.' },
  { id: 'be-09', name: 'Sentiers d\'Art', location: 'Gesves/Ohey', region: 'België', lat: 50.4125, lng: 5.1236, website: '#', shortDescription: 'Lange wandelroute (150km) met talloze landart werken.' },
  { id: 'be-10', name: 'Station d\'Art', location: 'Koksijde', region: 'België', lat: 51.1167, lng: 2.6333, website: '#', shortDescription: 'Kust/duin landart project.' },
  { id: 'be-11', name: 'La Louvière (Sculptuurpark)', location: 'La Louvière', region: 'België', lat: 50.4789, lng: 4.1889, website: '#', shortDescription: 'Openluchtmuseum voor stedelijke sculptuur.' },
  { id: 'be-12', name: 'Parc de Sculpture d\'Hanswijk', location: 'Mechelen', region: 'België', lat: 51.0200, lng: 4.4850, website: '#', shortDescription: 'Stadspark met beeldende kunst.' },
  { id: 'be-13', name: 'Grand-Hornu (Buitenlocaties)', location: 'Boussu', region: 'België', lat: 50.4350, lng: 3.8390, website: '#', shortDescription: 'Industrieel erfgoed ontmoet hedendaagse kunst.' },
  { id: 'be-14', name: 'Vrijbroekpark (Beelden)', location: 'Mechelen', region: 'België', lat: 51.0150, lng: 4.4680, website: '#', shortDescription: 'Landschapspark met sculpturale accenten.' },
  { id: 'be-15', name: 'Park van Vorst', location: 'Brussel', region: 'België', lat: 50.8228, lng: 4.3314, website: '#', shortDescription: 'Landschappelijke beelden in een Brussels park.' },
  { id: 'be-16', name: 'L\'Espace d\'Art Contemporain (EAC)', location: 'Oupeye', region: 'België', lat: 50.7083, lng: 5.6439, website: '#', shortDescription: 'Kasteelpark met wisselende sculpturen.' },
  { id: 'lux-01', name: 'Mudam Sculpture Garden', location: 'Luxemburg-Stad', region: 'Luxemburg', lat: 49.6169, lng: 6.1394, website: '#', shortDescription: 'Moderne beelden rondom het museumgebouw.' },
  { id: 'lux-02', name: 'Lultzhausen (Landart route)', location: 'Lultzhausen', region: 'Luxemburg', lat: 49.9083, lng: 5.8867, website: '#', shortDescription: 'Kunst aan de oever van de Sûre.' },
  { id: 'lux-03', name: 'Burfelt Nature Centre', location: 'Insenborn', region: 'Luxemburg', lat: 49.8944, lng: 5.8500, website: '#', shortDescription: 'Boskunst en landart in een natuurlijke setting.' },
  { id: 'lux-04', name: 'Steinfort (Beeldenpad)', location: 'Steinfort', region: 'Luxemburg', lat: 49.6600, lng: 5.9150, website: '#', shortDescription: 'Grensroute met beeldhouwwerken.' },
  { id: 'lux-05', name: 'Kuebebierg (Landart site)', location: 'Luxemburg-Stad', region: 'Luxemburg', lat: 49.6280, lng: 6.1660, website: '#', shortDescription: 'Landart op het Kirchberg plateau.' },
  { id: 'lux-06', name: 'Parc de sculptures du Galgenberg', location: 'Esch-sur-Alzette', region: 'Luxemburg', lat: 49.4910, lng: 5.9860, website: '#', shortDescription: 'Heuvellandschap met monumentale sculpturen.' },

  // --- FRANKRIJK ---
  { id: 'fr-01', name: 'Le Serpent d\'Océan', location: 'Saint-Brevin-les-Pins', region: 'Frankrijk', lat: 47.2514, lng: 2.1556, website: '#', shortDescription: 'Monumentaal zeeslang-skelet in de oceaan.' },
  { id: 'fr-02', name: 'Château La Coste', location: 'Le Puy-Sainte-Réparade', region: 'Frankrijk', lat: 43.6475, lng: 5.4950, website: '#', shortDescription: 'Wereldklasse kunst en architectuur in de wijngaarden.' },
  { id: 'fr-03', name: 'Domaine de Kerguehennec', location: 'Bignan', region: 'Frankrijk', lat: 47.8864, lng: 2.8361, website: '#', shortDescription: 'Beeldenpark in een historisch Bretons landgoed.' },
  { id: 'fr-04', name: 'Centre international d\'art et du paysage', location: 'Beaumont-du-Lac', region: 'Frankrijk', lat: 45.8150, lng: 1.8650, website: '#', shortDescription: 'Île de Vassivière: Een eiland gewijd aan landart.' },
  { id: 'fr-05', name: 'Forêt d\'Art Contemporain', location: 'Dordogne', region: 'Frankrijk', lat: 44.1350, lng: 0.8650, website: '#', shortDescription: 'Verspreide kunstwerken in de uitgestrekte bossen.' },
  { id: 'fr-06', name: 'Parc du Bois des Moutiers', location: 'Varengeville-sur-Mer', region: 'Frankrijk', lat: 49.8895, lng: 0.9850, website: '#', shortDescription: 'Tuin en sculptuur aan de Normandische kust.' },
  { id: 'fr-07', name: 'Musée Rodin (Tuin)', location: 'Parijs', region: 'Frankrijk', lat: 48.8554, lng: 2.3168, website: '#', shortDescription: 'Iconische beeldentuin met meesterwerken van Rodin.' },
  { id: 'fr-08', name: 'Domaine du Muy', location: 'Le Muy', region: 'Frankrijk', lat: 43.4833, lng: 6.5917, website: '#', shortDescription: 'Privédomein met monumentale hedendaagse kunst.' },
  { id: 'fr-09', name: 'Jardin de Berchigranges', location: 'Granges-sur-Vologne', region: 'Frankrijk', lat: 48.1367, lng: 6.8647, website: '#', shortDescription: 'Privétuin met poëtische landart elementen.' },
  { id: 'fr-10', name: 'Chaos de Montfaucon', location: 'Montfaucon', region: 'Frankrijk', lat: 44.5772, lng: 4.7208, website: '#', shortDescription: 'Landschapskunst in een rotsachtige setting.' },
  { id: 'fr-11', name: 'Jardin des Géants', location: 'Lille', region: 'Frankrijk', lat: 50.6433, lng: 3.0655, website: '#', shortDescription: 'Botanische stadstuin met kunstzinnige installaties.' },
  { id: 'fr-12', name: 'Parc culturel de Rentilly', location: 'Collégien', region: 'Frankrijk', lat: 48.8475, lng: 2.6861, website: '#', shortDescription: 'Hedendaagse kunstpark in de regio Parijs.' },
  { id: 'fr-13', name: 'Abbaye de Fontfroide', location: 'Narbonne', region: 'Frankrijk', lat: 43.1092, lng: 2.8569, website: '#', shortDescription: 'Sculpturen in de tuinen van een historisch klooster.' },
  { id: 'fr-14', name: 'Château de Chaumont-sur-Loire', location: 'Chaumont-sur-Loire', region: 'Frankrijk', lat: 47.4794, lng: 1.1819, website: '#', shortDescription: 'Locus voor internationale tuinkunst.' },
  { id: 'fr-15', name: 'Vent des Forêts', location: 'Fresnes-au-Mont', region: 'Frankrijk', lat: 48.8753, lng: 5.3475, website: '#', shortDescription: 'Kunstcentrum in het bos met 45km aan wandelpaden.' },
  { id: 'fr-16', name: 'Vieux-La-Romaine', location: 'Vieux', region: 'Frankrijk', lat: 49.1121, lng: 0.3815, website: '#', shortDescription: 'Archeologiepark gecombineerd met landschapskunst.' },
  { id: 'fr-17', name: 'Parc Jean-Jacques Rousseau', location: 'Ermenonville', region: 'Frankrijk', lat: 49.1150, lng: 2.6850, website: '#', shortDescription: 'Historisch landschapspark met filosofische elementen.' },
  { id: 'fr-18', name: 'Le domaine de Tizé', location: 'Servon-sur-Vilaine', region: 'Frankrijk', lat: 48.1500, lng: 1.4833, website: '#', shortDescription: 'Experimentele kunstplek langs de rivier de Vilaine.' },
  { id: 'fr-19', name: 'Jardin de Dhuys', location: 'Haute-Marne', region: 'Frankrijk', lat: 48.7490, lng: 5.4510, website: '#', shortDescription: 'Grootschalige stenen sculpturen in de natuur.' },
  { id: 'fr-20', name: 'Forêt monumentale', location: 'Rouen', region: 'Frankrijk', lat: 49.4674, lng: 1.0664, website: '#', shortDescription: 'Route met monumentale kunst in het bos.' },
  { id: 'fr-21', name: 'Parc de la Villette', location: 'Parijs', region: 'Frankrijk', lat: 48.8950, lng: 2.3888, website: '#', shortDescription: 'Modern stadspark met iconische architecturale follies.' },
  { id: 'fr-22', name: 'Villa Arson', location: 'Nice', region: 'Frankrijk', lat: 43.7225, lng: 7.2600, website: '#', shortDescription: 'Kunstcentrum met beeldentuinen in de Côte d\'Azur.' },

  // --- SPANJE ---
  { id: 'es-01', name: 'Museo Lagomar', location: 'Nazaret (Lanzarote)', region: 'Spanje', lat: 29.0350, lng: -13.5656, website: '#', shortDescription: 'Architectuur en kunst in vulkanische grotten.' },
  { id: 'es-02', name: 'Jardín de Cactus', location: 'Guatiza (Lanzarote)', region: 'Spanje', lat: 29.0560, lng: -13.4862, website: '#', shortDescription: 'César Manrique\'s meesterlijke cactus-tuin.' },
  { id: 'es-03', name: 'Mirador del Rio', location: 'Haría (Lanzarote)', region: 'Spanje', lat: 29.2014, lng: -13.4912, website: '#', shortDescription: 'Spectaculair uitzichtpunt en architectonisch kunstwerk.' },
  { id: 'es-04', name: 'Taro de Tahíche', location: 'Tahíche (Lanzarote)', region: 'Spanje', lat: 29.0062, lng: -13.5594, website: '#', shortDescription: 'César Manrique Foundation: Woonhuis en beelden.' },
  { id: 'es-05', name: 'Fuerteventura Sculpture Park', location: 'Puerto del Rosario', region: 'Spanje', lat: 28.4969, lng: -13.8653, website: '#', shortDescription: 'Openlucht beeldenpark in de hoofdstad van Fuerteventura.' },
  { id: 'es-06', name: 'Malpaís de La Arena', location: 'La Oliva', region: 'Spanje', lat: 28.6000, lng: -13.8900, website: '#', shortDescription: 'Vulkanisch landschap met sculpturale accenten.' },
  { id: 'es-07', name: 'Las Médulas', location: 'Ponferrada', region: 'Spanje', lat: 42.5471, lng: -6.9427, website: '#', shortDescription: 'Romeinse goudmijn: Een door menshanden gevormd landschap.' },
  { id: 'es-08', name: 'Museo Vostell Malpartida', location: 'Malpartida de Cáceres', region: 'Spanje', lat: 39.3900, lng: -6.5200, website: '#', shortDescription: 'Fluxus en landart in Los Barruecos.' },
  { id: 'es-09', name: 'Chillida Leku', location: 'Hernani', region: 'Spanje', lat: 43.2383, lng: -1.9847, website: '#', shortDescription: 'Beeldenpark gewijd aan Eduardo Chillida.' },
  { id: 'es-10', name: 'Fundació Pilar i Joan Miró', location: 'Palma de Mallorca', region: 'Spanje', lat: 39.5539, lng: 2.6106, website: '#', shortDescription: 'Beeldentuin bij het atelier van Miró.' },
  { id: 'es-11', name: 'Parque Güell', location: 'Barcelona', region: 'Spanje', lat: 41.4147, lng: 2.1526, website: '#', shortDescription: 'Antoni Gaudí\'s beroemde modernistische park.' },
  { id: 'es-12', name: 'IVAM Beeldenpark', location: 'Valencia', region: 'Spanje', lat: 39.4755, lng: -0.3811, website: '#', shortDescription: 'Sculpturen bij het Instituut voor Moderne Kunst.' },
  { id: 'es-13', name: 'Parc Art', location: 'Les Oluges', region: 'Spanje', lat: 41.7483, lng: 1.2989, website: '#', shortDescription: 'Natuurkunstroute in het Catalaanse binnenland.' },
  { id: 'es-14', name: 'La Dehesa de la Villa', location: 'Madrid', region: 'Spanje', lat: 40.4578, lng: -3.7258, website: '#', shortDescription: 'Natuurlijk stadspark met beeldende elementen.' },
  { id: 'es-15', name: 'Parque del Retiro', location: 'Madrid', region: 'Spanje', lat: 40.4137, lng: -3.6811, website: '#', shortDescription: 'Historisch park met talloze monumentale sculpturen.' },
  { id: 'es-16', name: 'Parque Forestal Valdebebas', location: 'Madrid', region: 'Spanje', lat: 40.4851, lng: -3.6190, website: '#', shortDescription: 'Modern stadspark met landschapskunst.' },
  { id: 'es-17', name: 'Museo al Aire Libre', location: 'Madrid', region: 'Spanje', lat: 40.4431, lng: -3.6931, website: '#', shortDescription: 'Openlucht sculptuur museum onder een brug.' },
  { id: 'es-18', name: 'Juan Carlos I Park', location: 'Madrid', region: 'Spanje', lat: 40.4664, lng: -3.5855, website: '#', shortDescription: 'Groot openbaar park met moderne beelden.' },
  { id: 'es-19', name: 'Campo del Moro Tuinen', location: 'Madrid', region: 'Spanje', lat: 40.4172, lng: -3.7154, website: '#', shortDescription: 'Historische paleistuinen met beelden.' },
  { id: 'es-20', name: 'Jardín Botánico de Madrid', location: 'Madrid', region: 'Spanje', lat: 40.4075, lng: -3.6923, website: '#', shortDescription: 'Botanische tuinkunst.' },

  // --- ZWITSERLAND ---
  { id: 'ch-01', name: 'Fondation Gianadda (Park)', location: 'Martigny', region: 'Zwitserland', lat: 46.0945, lng: 7.0706, website: '#', shortDescription: 'Beeldentuin van wereldklasse met o.a. Rodin en Moore.' },
  { id: 'ch-02', name: 'Stiftung Sculpture at Schoenthal', location: 'Langenbruck', region: 'Zwitserland', lat: 47.3486, lng: 7.7667, website: '#', shortDescription: 'Landart op een oud kloosterterrein.' },
  { id: 'ch-03', name: 'Fondation Pierre Arnaud', location: 'Lens', region: 'Zwitserland', lat: 46.2798, lng: 7.4475, website: '#', shortDescription: 'Beeldenpark rondom een bergmeer.' },
  { id: 'ch-04', name: 'Art Safiental', location: 'Safien Platz', region: 'Zwitserland', lat: 46.6666, lng: 9.2882, website: '#', shortDescription: 'Biënnale voor landart in de hoge Alpen.' },
  { id: 'ch-05', name: 'L’Art et la Nature (Jorat)', location: 'Vaud', region: 'Zwitserland', lat: 46.5910, lng: 6.6850, website: '#', shortDescription: 'Boskunst-route in de regio Jorat.' },
  { id: 'ch-06', name: 'Muranarte', location: 'Vaud', region: 'Zwitserland', lat: 46.3833, lng: 6.9667, website: '#', shortDescription: 'Landart op Zwitserse bergpaden.' },
  { id: 'ch-07', name: 'Muzeum Susch', location: 'Susch', region: 'Zwitserland', lat: 46.7495, lng: 10.0811, website: '#', shortDescription: 'Kunst in een spectaculair architectonisch berglandschap.' },
  { id: 'ch-08', name: 'Parco delle Sculture', location: 'Ticino', region: 'Zwitserland', lat: 46.5167, lng: 8.8333, website: '#', shortDescription: 'Sculture in de vrije natuur van Ticino.' },
  { id: 'ch-09', name: 'Fondation Beyeler (Park)', location: 'Riehen', region: 'Zwitserland', lat: 47.5881, lng: 7.6511, website: '#', shortDescription: 'Sculpturen in de museumtuin bij Bazel.' },
  { id: 'ch-10', name: 'Steinbruch Gabenchopf', location: 'Villigen', region: 'Zwitserland', lat: 47.5251, lng: 8.2166, website: '#', shortDescription: 'Kunst in een actieve steengroeve.' },
  { id: 'ch-11', name: 'Skulpturenweg Wartegg', location: 'Rorschacherberg', region: 'Zwitserland', lat: 47.4795, lng: 9.5100, website: '#', shortDescription: 'Kunstroute door een historisch kasteelpark.' },
  { id: 'ch-12', name: 'Global Stone Project', location: 'Zürich', region: 'Zwitserland', lat: 47.3769, lng: 8.5417, website: '#', shortDescription: 'Meditatieve steenkunst in de stad.' },

  // --- ITALIË ---
  { id: 'it-01', name: 'Arte Sella', location: 'Borgo Valsugana', region: 'Italië', lat: 46.0125, lng: 11.5238, website: '#', shortDescription: 'Natuur en kunst verbonden in de Malga Costa.' },
  { id: 'it-02', name: 'Il Giardino dei Tarocchi', location: 'Capalbio', region: 'Italië', lat: 42.4248, lng: 11.4667, website: '#', shortDescription: 'Niki de Saint Phalle\'s esoterische beeldenpark.' },
  { id: 'it-03', name: 'Cretto di Burri', location: 'Gibellina', region: 'Italië', lat: 37.7915, lng: 12.9734, website: '#', shortDescription: 'Grootste landart-werk ter wereld ( Gibellina Vecchia).' },
  { id: 'it-04', name: 'Fattoria di Celle', location: 'Pistoia', region: 'Italië', lat: 43.9312, lng: 10.9856, website: '#', shortDescription: 'De beroemde Gori-collectie met site-specific kunst.' },
  { id: 'it-05', name: 'Giardino di Daniel Spoerri', location: 'Seggiano', region: 'Italië', lat: 42.9285, lng: 11.5658, website: '#', shortDescription: 'Surrealistisch beeldenpark in de Toscaanse heuvels.' },
  { id: 'it-06', name: 'RespirArt', location: 'Pampeago', region: 'Italië', lat: 46.2995, lng: 11.5432, website: '#', shortDescription: 'Hoogstgelegen landart-park in de Dolomieten.' },
  { id: 'it-07', name: 'Parco Sculture del Chianti', location: 'Pievasciata', region: 'Italië', lat: 43.3934, lng: 11.3937, website: '#', shortDescription: 'Hedendaagse kunst in een prachtig eikenbos.' },
  { id: 'it-08', name: 'Fiumara d\'Arte', location: 'Motta d\'Affermo', region: 'Italië', lat: 37.9863, lng: 14.3168, website: '#', shortDescription: 'Monumentale kustroute met sculpturen op Sicilië.' },
  { id: 'it-09', name: 'Labirinto della Masone', location: 'Fontanellato', region: 'Italië', lat: 44.8519, lng: 10.1581, website: '#', shortDescription: 'Grootste bamboe-doolhof ter wereld met kunstcollectie.' },
  { id: 'it-10', name: 'Parco Arte Vivente (PAV)', location: 'Turijn', region: 'Italië', lat: 45.0344, lng: 7.6711, website: '#', shortDescription: 'Bio-kunst en landart centrum.' },
  { id: 'it-11', name: 'Art Park La Court', location: 'Castelnuovo Calcea', region: 'Italië', lat: 44.7892, lng: 8.2861, website: '#', shortDescription: 'Landart tussen de wijngaarden.' },
  { id: 'it-12', name: 'Selva di Sogno', location: 'Chiusdino', region: 'Italië', lat: 43.1558, lng: 11.0858, website: '#', shortDescription: 'Meditatieve boskunst van Deva Manfredo.' },
  { id: 'it-13', name: 'Campo del Sole', location: 'Tuoro sul Trasimeno', region: 'Italië', lat: 43.1974, lng: 12.0831, website: '#', shortDescription: '43 sculpturale zuilen aan het Trasimenomeer.' },
  { id: 'it-14', name: 'Parco di Pinocchio', location: 'Collodi', region: 'Italië', lat: 43.8903, lng: 10.6558, website: '#', shortDescription: 'Artistiek en literair landschap.' },

  // --- OOSTENRIJK ---
  { id: 'at-01', name: 'Austrian Sculpture Park', location: 'Premstätten', region: 'Oostenrijk', lat: 46.9614, lng: 15.4856, website: '#', shortDescription: '7 hectare topcollectie hedendaagse kunst.' },
  { id: 'at-02', name: 'Skulpturenpark Schloss Grafenegg', location: 'Grafenegg', region: 'Oostenrijk', lat: 48.4283, lng: 15.7483, website: '#', shortDescription: 'Openluchtkunst in een historisch kasteelpark.' },
  { id: 'at-03', name: 'Waldskulpturenweg St. Georgen', location: 'St. Georgen', region: 'Oostenrijk', lat: 47.2081, lng: 14.4981, website: '#', shortDescription: 'Monumentale houtsculpturen in het bos.' },
  { id: 'at-04', name: 'Skulpturenweg Seeham', location: 'Seeham', region: 'Oostenrijk', lat: 47.9642, lng: 13.0764, website: '#', shortDescription: 'Kunstroute langs de Obertrumer See.' },
  { id: 'at-05', name: 'Gironcoli-Museum', location: 'Stubenberg am See', region: 'Oostenrijk', lat: 47.2189, lng: 15.7656, website: '#', shortDescription: 'Monumentale sculpturen van Bruno Gironcoli.' },
  { id: 'at-06', name: 'Donaupark Skulpturen', location: 'Wenen', region: 'Oostenrijk', lat: 48.2403, lng: 16.4092, website: '#', shortDescription: 'Openlucht galerie langs de Donau.' },
  { id: 'at-07', name: 'Skulpturengarten Belvedere 21', location: 'Wenen', region: 'Oostenrijk', lat: 48.1855, lng: 16.3833, website: '#', shortDescription: 'Hedendaagse buitenkunst in Wenen.' },
  { id: 'at-08', name: 'LandArt am Hochreiter', location: 'Breitenau', region: 'Oostenrijk', lat: 47.3881, lng: 15.4333, website: '#', shortDescription: 'Natuurkunst op grote hoogte.' },
  { id: 'at-09', name: 'Skulpturenpark Leogang', location: 'Leogang', region: 'Oostenrijk', lat: 47.4389, lng: 12.7533, website: '#', shortDescription: 'Kunst op de Alpenweiden (Sinnlehenalm).' }
];
