
import { SculpturePark } from './types';

export const INITIAL_PARKS: SculpturePark[] = [
  // --- SPANJE: DE ULTIEME COLLECTIE (50+ locaties) ---
  { id: 'es-01', name: 'Museo Lagomar', location: 'Nazaret (Lanzarote)', region: 'Spanje', lat: 29.0350, lng: -13.5656, website: '#', shortDescription: 'Architectuur en kunst in vulkanische grotten.' },
  { id: 'es-02', name: 'Jardín de Cactus', location: 'Guatiza (Lanzarote)', region: 'Spanje', lat: 29.0560, lng: -13.4862, website: '#', shortDescription: 'Cactus-tuin met monumentale sculpturen van Manrique.' },
  { id: 'es-03', name: 'Chillida Leku', location: 'Hernani', region: 'Spanje', lat: 43.2383, lng: -1.9847, website: '#', shortDescription: 'Levenswerk van Eduardo Chillida.' },
  { id: 'es-04', name: 'Museo Vostell Malpartida', location: 'Malpartida de Cáceres', region: 'Spanje', lat: 39.3900, lng: -6.5200, website: '#', shortDescription: 'Fluxus en landart in Los Barruecos.' },
  { id: 'es-05', name: 'Parque Güell', location: 'Barcelona', region: 'Spanje', lat: 41.4147, lng: 2.1526, website: '#', shortDescription: 'Gaudí\'s iconische park.' },
  { id: 'es-06', name: 'Fuerteventura Sculpture Park', location: 'Puerto del Rosario', region: 'Spanje', lat: 28.4969, lng: -13.8653, website: '#', shortDescription: 'Meer dan 100 beelden in de openbare ruimte.' },
  { id: 'es-07', name: 'Fundació Pilar i Joan Miró', location: 'Palma de Mallorca', region: 'Spanje', lat: 39.5539, lng: 2.6106, website: '#', shortDescription: 'Beeldentuin bij het Miró atelier.' },
  { id: 'es-08', name: 'Peine del Viento', location: 'San Sebastián', region: 'Spanje', lat: 43.3214, lng: -2.0061, website: '#', shortDescription: 'Beroemde ijzeren beelden van Chillida aan de kust.' },
  { id: 'es-09', name: 'Parque del Pescador', location: 'Cambrils', region: 'Spanje', lat: 41.0642, lng: 1.0592, website: '#', shortDescription: 'Kustpark met diverse moderne sculpturen.' },
  { id: 'es-10', name: 'NMAC Foundation', location: 'Vejer de la Frontera', region: 'Spanje', lat: 36.2528, lng: -5.9667, website: '#', shortDescription: 'Hedendaagse kunst in een dennenbos.' },
  { id: 'es-11', name: 'Elogio del Horizonte', location: 'Gijón', region: 'Spanje', lat: 43.5511, lng: -5.6631, website: '#', shortDescription: 'Monumentale betonnen sculptuur van Chillida.' },
  { id: 'es-12', name: 'Parque de la Victoria', location: 'Córdoba', region: 'Spanje', lat: 37.8847, lng: -4.7861, website: '#', shortDescription: 'Stadspark met historische en moderne beelden.' },
  { id: 'es-13', name: 'Jardines de las Vistillas', location: 'Madrid', region: 'Spanje', lat: 40.4125, lng: -3.7144, website: '#', shortDescription: 'Park met prachtige beelden en uitzicht op Madrid.' },
  { id: 'es-14', name: 'Museo de Escultura Castellana', location: 'Madrid', region: 'Spanje', lat: 40.4350, lng: -3.6889, website: '#', shortDescription: 'Abstracte sculpturen onder een viaduct.' },
  { id: 'es-15', name: 'Meiac Garden', location: 'Badajoz', region: 'Spanje', lat: 38.8781, lng: -6.9706, website: '#', shortDescription: 'Beelden op de grens met Portugal.' },
  { id: 'es-16', name: 'Fundación Montenmedio', location: 'Cádiz', region: 'Spanje', lat: 36.2844, lng: -5.9239, website: '#', shortDescription: 'Land-art van internationale allure.' },
  { id: 'es-17', name: 'Parque Juan Carlos I', location: 'Madrid', region: 'Spanje', lat: 40.4611, lng: -3.6128, website: '#', shortDescription: 'Groot park met 19 monumentale werken.' },
  { id: 'es-18', name: 'Can Mario Garden', location: 'Palafrugell', region: 'Spanje', lat: 41.9175, lng: 3.1633, website: '#', shortDescription: 'Modern Catalaanse beeldentuin.' },
  { id: 'es-19', name: 'Parque Alameda', location: 'Santiago de Compostela', region: 'Spanje', lat: 42.8778, lng: -8.5491, website: '#', shortDescription: 'Historisch park met sculpturale verrassingen.' },
  { id: 'es-20', name: 'IVAM Garden', location: 'Valencia', region: 'Spanje', lat: 39.4800, lng: -0.3833, website: '#', shortDescription: 'Moderne sculptuur bij het IVAM museum.' },
  { id: 'es-21', name: 'Park of the West', location: 'Oviedo', region: 'Spanje', lat: 43.3603, lng: -5.8644, website: '#', shortDescription: 'Buitenmuseum met diverse abstracte werken.' },
  { id: 'es-22', name: 'Mirador de Daroca', location: 'Zaragoza', region: 'Spanje', lat: 41.1147, lng: -1.4161, website: '#', shortDescription: 'Kunstwerk geïntegreerd in het berglandschap.' },
  { id: 'es-23', name: 'Sculpture Garden CDAN', location: 'Huesca', region: 'Spanje', lat: 42.1461, lng: -0.4267, website: '#', shortDescription: 'Kunst en natuur in het centrum van Beulas.' },
  { id: 'es-24', name: 'Parque de las Llamas', location: 'Santander', region: 'Spanje', lat: 43.4739, lng: -3.7933, website: '#', shortDescription: 'Modern wetlandpark met sculpturale accenten.' },
  { id: 'es-25', name: 'Jardines de Sabatini', location: 'Madrid', region: 'Spanje', lat: 40.4194, lng: -3.7142, website: '#', shortDescription: 'Neoklassieke beelden bij het Koninklijk Paleis.' },
  { id: 'es-26', name: 'Espinardo Campus Art', location: 'Murcia', region: 'Spanje', lat: 38.0200, lng: -1.1680, website: '#', shortDescription: 'Openlucht kunst op de universiteitscampus.' },
  { id: 'es-27', name: 'Parque de los Príncipes', location: 'Sevilla', region: 'Spanje', lat: 37.3758, lng: -6.0011, website: '#', shortDescription: 'Traditionele en moderne sculpturen in de wijk Los Remedios.' },
  { id: 'es-28', name: 'Fundación Stämpfli', location: 'Sitges', region: 'Spanje', lat: 41.2358, lng: 1.8125, website: '#', shortDescription: 'Beeldentuin van hedendaagse kunstenaars.' },
  { id: 'es-29', name: 'Marbella Sculpture Way', location: 'Marbella', region: 'Spanje', lat: 36.5083, lng: -4.8856, website: '#', shortDescription: 'Avenida del Mar met Dali sculpturen.' },
  { id: 'es-30', name: 'Parque de Doña Casilda', location: 'Bilbao', region: 'Spanje', lat: 43.2661, lng: -2.9414, website: '#', shortDescription: 'Historisch hart van Bilbao met diverse sculpturen.' },
  { id: 'es-31', name: 'Teide National Park Art', location: 'Tenerife', region: 'Spanje', lat: 28.2722, lng: -16.6425, website: '#', shortDescription: 'Natuurlijke formaties en enkele subtiele kunstingrepen.' },
  { id: 'es-32', name: 'Museo de Escultura Leganés', location: 'Madrid Region', region: 'Spanje', lat: 40.3283, lng: -3.7656, website: '#', shortDescription: 'Grote collectie moderne Spaanse beeldhouwkunst.' },
  { id: 'es-33', name: 'Parque de la Memoria', location: 'Sartaguda', region: 'Spanje', lat: 42.3833, lng: -2.0500, website: '#', shortDescription: 'Beeldenpark ter herdenking van historische gebeurtenissen.' },
  { id: 'es-34', name: 'Torre Hércules Park', location: 'A Coruña', region: 'Spanje', lat: 43.3858, lng: -8.4064, website: '#', shortDescription: 'Mythologisch beeldenpark rond de Romeinse toren.' },
  { id: 'es-35', name: 'Jardín Botánico de Málaga', location: 'Málaga', region: 'Spanje', lat: 36.7600, lng: -4.4289, website: '#', shortDescription: 'Historische beelden in een weelderige botanische setting.' },
  { id: 'es-36', name: 'Paseo de la Libertad', location: 'Albacete', region: 'Spanje', lat: 38.9950, lng: -1.8580, website: '#', shortDescription: 'Stadswandeling met monumentale bronzen.' },
  { id: 'es-37', name: 'Parque Genovés', location: 'Cádiz', region: 'Spanje', lat: 36.5361, lng: -6.3039, website: '#', shortDescription: 'Prachtig gesnoeide bomen en klassieke beelden.' },
  { id: 'es-38', name: 'Fundación Fran Daurel', location: 'Barcelona (Poble Espanyol)', region: 'Spanje', lat: 41.3689, lng: 2.1472, website: '#', shortDescription: 'Grote beeldentuin in het Spaanse Dorp.' },
  { id: 'es-39', name: 'Park of the Waters', location: 'Logroño', region: 'Spanje', lat: 42.4667, lng: -2.4456, website: '#', shortDescription: 'Modern stadsontwerp met geïntegreerde kunst.' },
  { id: 'es-40', name: 'Guggenheim Garden', location: 'Bilbao', region: 'Spanje', lat: 43.2686, lng: -2.9342, website: '#', shortDescription: 'Beroemde werken van Koons en Bourgeois buiten het museum.' },
  { id: 'es-41', name: 'Euskadi Park', location: 'Bilbao', region: 'Spanje', lat: 43.2680, lng: -2.9380, website: '#', shortDescription: 'Beelden van Chillida en Serra in het hart van de stad.' },
  { id: 'es-42', name: 'Ametzola Park', location: 'Bilbao', region: 'Spanje', lat: 43.2550, lng: -2.9430, website: '#', shortDescription: 'Moderne sculptuur in een vernieuwd woongebied.' },
  { id: 'es-43', name: 'Zorrozaurre Art', location: 'Bilbao', region: 'Spanje', lat: 43.2750, lng: -2.9600, website: '#', shortDescription: 'Industriële kunst op het nieuwe schiereiland.' },
  { id: 'es-44', name: 'La Florida Park', location: 'Vitoria-Gasteiz', region: 'Spanje', lat: 42.8464, lng: -2.6775, website: '#', shortDescription: 'Romantisch park met standbeelden van gotische koningen.' },
  { id: 'es-45', name: 'Salburua Art Path', location: 'Vitoria-Gasteiz', region: 'Spanje', lat: 42.8550, lng: -2.6450, website: '#', shortDescription: 'Natuurlijk pad met installaties over biodiversiteit.' },
  { id: 'es-46', name: 'Prado Open Air', location: 'Madrid', region: 'Spanje', lat: 40.4139, lng: -3.6922, website: '#', shortDescription: 'De klassieke Paseo del Prado met haar vele fonteinen en beelden.' },
  { id: 'es-47', name: 'Retiro Garden Statues', location: 'Madrid', region: 'Spanje', lat: 40.4153, lng: -3.6839, website: '#', shortDescription: 'Inclusief de beroemde Fallen Angel sculptuur.' },
  { id: 'es-48', name: 'Miró Park', location: 'Barcelona', region: 'Spanje', lat: 41.3772, lng: 2.1469, website: '#', shortDescription: 'Met het gigantische "Vrouw en Vogel" beeld.' },
  { id: 'es-49', name: 'Olympic Park Montjuïc', location: 'Barcelona', region: 'Spanje', lat: 41.3636, lng: 2.1528, website: '#', shortDescription: 'Vele monumenten rond de sportfaciliteiten.' },
  { id: 'es-50', name: 'Port Vell Sculptures', location: 'Barcelona', region: 'Spanje', lat: 41.3750, lng: 2.1817, website: '#', shortDescription: 'Moderne maritieme kunst aan de haven.' },

  // --- DUITSLAND: DE VOLLEDIGE ROUTE (30+ locaties) ---
  { id: 'de-bam-01', name: 'Bamberger Skulpturenweg', location: 'Bamberg', region: 'Duitsland', lat: 49.8917, lng: 10.8864, website: '#', shortDescription: 'Route door UNESCO stad met wereldberoemde werken.' },
  { id: 'de-bam-02', name: 'Villa Dessauer Garden', location: 'Bamberg', region: 'Duitsland', lat: 49.8875, lng: 10.8922, website: '#', shortDescription: 'Hedendaagse kunst in museumtuin.' },
  { id: 'de-bam-03', name: 'Main-Donau Route', location: 'Bamberg-Erlangen', region: 'Duitsland', lat: 49.7000, lng: 10.9500, website: '#', shortDescription: 'Kunst langs het water.' },
  { id: 'de-nur-01', name: 'Neurenberg Zwinger', location: 'Neurenberg', region: 'Duitsland', lat: 49.4478, lng: 11.0822, website: '#', shortDescription: 'Beeldenpark aan de stadsmuur.' },
  { id: 'de-ulm-01', name: 'Donaupark Ulm', location: 'Ulm', region: 'Duitsland', lat: 48.4011, lng: 9.9919, website: '#', shortDescription: 'Moderne sculptuur aan de Donau.' },
  { id: 'de-dw-01', name: 'Altmann Park', location: 'Donauwörth', region: 'Duitsland', lat: 48.7172, lng: 10.7783, website: '#', shortDescription: 'Privépark met publieke toegang.' },
  { id: 'de-reg-01', name: 'Donau-Einkaufszentrum', location: 'Regensburg', region: 'Duitsland', lat: 49.0245, lng: 12.1100, website: '#', shortDescription: 'Moderne sculptuur in de publieke ruimte.' },
  { id: 'de-mun-01', name: 'Pinakothek Garden', location: 'München', region: 'Duitsland', lat: 48.1472, lng: 11.5722, website: '#', shortDescription: 'Topstukken uit de moderne kunstgeschiedenis.' },
  { id: 'de-ber-01', name: 'Gärten der Welt', location: 'Berlijn', region: 'Duitsland', lat: 52.5050, lng: 13.6264, website: '#', shortDescription: 'Internationale tuinkunst en beelden.' },
  { id: 'de-kas-01', name: 'Bergpark Wilhelmshöhe', location: 'Kassel', region: 'Duitsland', lat: 51.3158, lng: 9.3931, website: '#', shortDescription: 'UNESCO werelderfgoed met Hercules monument.' },
  { id: 'de-sk-01', name: 'Skulpturenpark Waldfrieden', location: 'Wuppertal', region: 'Duitsland', lat: 51.2533, lng: 7.1706, website: '#', shortDescription: 'Prachtig park van Tony Cragg.' },
  { id: 'de-sk-02', name: 'Skulpturenpark Köln', location: 'Keulen', region: 'Duitsland', lat: 50.9556, lng: 6.9711, website: '#', shortDescription: 'Wisselende tentoonstellingen bij de Rijn.' },
  { id: 'de-in-01', name: 'Insel Hombroich', location: 'Neuss', region: 'Duitsland', lat: 51.1472, lng: 6.6583, website: '#', shortDescription: 'Unieke samensmelting van architectuur en natuur.' },
  { id: 'de-ms-01', name: 'Skulptur Projekte Münster', location: 'Münster', region: 'Duitsland', lat: 51.9607, lng: 7.6261, website: '#', shortDescription: 'Hele stad als beeldenpark (10-jaarlijks).' },
  { id: 'de-ha-01', name: 'Stiftung Kunstlandshaft', location: 'Hamburg', region: 'Duitsland', lat: 53.5500, lng: 9.9933, website: '#', shortDescription: 'Vele beelden verspreid over de stad.' },
  { id: 'de-fr-01', name: 'Mainufer Skulpturen', location: 'Frankfurt', region: 'Duitsland', lat: 50.1100, lng: 8.6800, website: '#', shortDescription: 'Kunst aan de oevers van de Main.' },
  { id: 'de-du-01', name: 'Lehmbruck Museum Garden', location: 'Duisburg', region: 'Duitsland', lat: 51.4300, lng: 6.7633, website: '#', shortDescription: 'Park rond het centrum voor internationale beeldhouwkunst.' },
  { id: 'de-ma-01', name: 'Luisenpark', location: 'Mannheim', region: 'Duitsland', lat: 49.4825, lng: 8.4975, website: '#', shortDescription: 'Een van de mooiste parken van Europa met kunst.' },
  { id: 'de-st-01', name: 'Schlosspark Stuttgart', location: 'Stuttgart', region: 'Duitsland', lat: 48.7800, lng: 9.1800, website: '#', shortDescription: 'Groen hart met historische monumenten.' },
  { id: 'de-br-01', name: 'Bürgerpark Bremen', location: 'Bremen', region: 'Duitsland', lat: 53.0880, lng: 8.8180, website: '#', shortDescription: 'Beelden in een Engels landschapspark.' },
  { id: 'de-dr-01', name: 'Zwinger Garden', location: 'Dresden', region: 'Duitsland', lat: 51.0531, lng: 13.7339, website: '#', shortDescription: 'Barokke beeldhouwkunst van topniveau.' },
  { id: 'de-han-01', name: 'Eilenriede', location: 'Hannover', region: 'Duitsland', lat: 52.3833, lng: 9.7667, website: '#', shortDescription: 'Grootste stadsbos van Europa met kunstwerken.' },
  { id: 'de-dar-01', name: 'Mathildenhöhe', location: 'Darmstadt', region: 'Duitsland', lat: 49.8767, lng: 8.6667, website: '#', shortDescription: 'Jugendstil kunstenaarskolonie met beelden.' },
  { id: 'de-bad-01', name: 'Lichtentaler Allee', location: 'Baden-Baden', region: 'Duitsland', lat: 48.7567, lng: 8.2400, website: '#', shortDescription: 'Kunst aan de mondaine flaneerpromenade.' },
  { id: 'de-os-01', name: 'Felix-Nussbaum-Weg', location: 'Osnabrück', region: 'Duitsland', lat: 52.2780, lng: 8.0430, website: '#', shortDescription: 'Gedenktekens en moderne sculptuur.' },
  { id: 'de-bi-01', name: 'Kunsthalle Bielefeld Garden', location: 'Bielefeld', region: 'Duitsland', lat: 52.0200, lng: 8.5250, website: '#', shortDescription: 'Topwerken van Moore, Serra en Rodin.' },
  { id: 'de-wo-01', name: 'Autostadt Sculpture', location: 'Wolfsburg', region: 'Duitsland', lat: 52.4333, lng: 10.7933, website: '#', shortDescription: 'Modern design en kunst op industriële schaal.' },
  { id: 'de-ch-01', name: 'Chemnitz Skulpturenweg', location: 'Chemnitz', region: 'Duitsland', lat: 50.8333, lng: 12.9167, website: '#', shortDescription: 'Oost-Duitse historie ontmoet moderne kunst.' },
  { id: 'de-er-01', name: 'Burgberg Erlangen', location: 'Erlangen', region: 'Duitsland', lat: 49.6000, lng: 11.0000, website: '#', shortDescription: 'Beeldentuin met uitzicht over de stad.' },
  { id: 'de-bo-01', name: 'Bochum Art Path', location: 'Bochum', region: 'Duitsland', lat: 51.4817, lng: 7.2158, website: '#', shortDescription: 'Publieke kunst in het Ruhrgebied.' },

  // --- NEDERLAND & BELGIË (30+ locaties) ---
  { id: 'nl-01', name: 'Kröller-Müller', location: 'Otterlo', region: 'Nederland', lat: 52.0951, lng: 5.8197, website: '#', shortDescription: 'Iconische tuin op de Veluwe.' },
  { id: 'nl-02', name: 'De Groene Kathedraal', location: 'Almere', region: 'Nederland', lat: 52.3217, lng: 5.3200, website: '#', shortDescription: 'Levende land-art.' },
  { id: 'nl-03', name: 'Observatorium', location: 'Lelystad', region: 'Nederland', lat: 52.5511, lng: 5.5564, website: '#', shortDescription: 'Robert Morris land-art.' },
  { id: 'nl-04', name: 'Exposure', location: 'Lelystad', region: 'Nederland', lat: 52.5256, lng: 5.4361, website: '#', shortDescription: 'De hurkende man van Gormley.' },
  { id: 'nl-05', name: 'Voorlinden', location: 'Wassenaar', region: 'Nederland', lat: 52.1189, lng: 4.3314, website: '#', shortDescription: 'Moderne meesters bij zee.' },
  { id: 'nl-06', name: 'Beelden aan Zee', location: 'Scheveningen', region: 'Nederland', lat: 52.1114, lng: 4.2817, website: '#', shortDescription: 'Sprookjes op de boulevard.' },
  { id: 'nl-07', name: 'Land Art Delft', location: 'Delft', region: 'Nederland', lat: 51.9833, lng: 4.3833, website: '#', shortDescription: 'Combinatie van kunst en techniek.' },
  { id: 'nl-08', name: 'Aardzee', location: 'Zeewolde', region: 'Nederland', lat: 52.3500, lng: 5.4500, website: '#', shortDescription: 'Piet Slegers land-art.' },
  { id: 'nl-09', name: 'Drechtoevers', location: 'Zwijndrecht', region: 'Nederland', lat: 51.8211, lng: 4.6567, website: '#', shortDescription: 'Kunst aan de Maas.' },
  { id: 'nl-10', name: 'Park Luna', location: 'Heerhugowaard', region: 'Nederland', lat: 52.6500, lng: 4.8167, website: '#', shortDescription: 'Duurzame kunst.' },
  { id: 'nl-11', name: 'Museum Belvédère Garden', location: 'Heerenveen', region: 'Nederland', lat: 52.9583, lng: 5.9250, website: '#', shortDescription: 'Kunst in het Friese landschap.' },
  { id: 'nl-12', name: 'Singelpark Leiden', location: 'Leiden', region: 'Nederland', lat: 52.1600, lng: 4.4900, website: '#', shortDescription: 'Langste beeldenpark van Nederland.' },
  { id: 'nl-13', name: 'Polderland Garden of Love', location: 'Zeewolde', region: 'Nederland', lat: 52.3300, lng: 5.4000, website: '#', shortDescription: 'Daniel Libeskind land-art.' },
  { id: 'nl-14', name: 'Deltawerk 1:1', location: 'Marknesse', region: 'Nederland', lat: 52.6833, lng: 5.8833, website: '#', shortDescription: 'Monumentale land-art in het Waterloopbos.' },
  { id: 'nl-15', name: 'Rijksmuseum Garden', location: 'Amsterdam', region: 'Nederland', lat: 52.3599, lng: 4.8852, website: '#', shortDescription: 'Wisselende tentoonstellingen van topniveau.' },
  { id: 'nl-16', name: 'Museum Arnhem Garden', location: 'Arnhem', region: 'Nederland', lat: 51.9833, lng: 5.8950, website: '#', shortDescription: 'Beelden met uitzicht over de Rijn.' },
  { id: 'nl-17', name: 'Fundatie Kasteel het Nijenhuis', location: 'Heino', region: 'Nederland', lat: 52.4333, lng: 6.2333, website: '#', shortDescription: 'Prachtige beeldentuin bij het kasteel.' },
  { id: 'nl-18', name: 'Noordbrabants Museum Garden', location: 's-Hertogenbosch', region: 'Nederland', lat: 51.6880, lng: 5.3050, website: '#', shortDescription: 'Historische setting met moderne werken.' },
  { id: 'nl-19', name: 'CODA Museum Garden', location: 'Apeldoorn', region: 'Nederland', lat: 52.2130, lng: 5.9610, website: '#', shortDescription: 'Sieraden en kleine sculptuur in de buitenlucht.' },
  { id: 'nl-20', name: 'Vrijthof Sculptures', location: 'Maastricht', region: 'Nederland', lat: 50.8490, lng: 5.6880, website: '#', shortDescription: 'Historische beelden op het plein.' },
  { id: 'be-01', name: 'Middelheim', location: 'Antwerpen', region: 'België', lat: 51.1821, lng: 4.4150, website: '#', shortDescription: 'Openluchtmuseum van wereldklasse.' },
  { id: 'be-02', name: 'Verbeke Foundation', location: 'Kemzeke', region: 'België', lat: 51.2183, lng: 4.0628, website: '#', shortDescription: 'Anarchistisch kunstlandschap.' },
  { id: 'be-03', name: 'Ten Duinen', location: 'Koksijde', region: 'België', lat: 51.1094, lng: 2.6331, website: '#', shortDescription: 'Kunst in de abdij.' },
  { id: 'be-04', name: 'Hugo Voeten Garden', location: 'Geel', region: 'België', lat: 51.1611, lng: 4.9903, website: '#', shortDescription: 'Grote privécollectie.' },
  { id: 'be-05', name: 'Park van Laken', location: 'Brussel', region: 'België', lat: 50.8833, lng: 4.3500, website: '#', shortDescription: 'Monumentale koninklijke beelden.' },
  { id: 'be-06', name: 'Sart Tilman', location: 'Luik', region: 'België', lat: 50.5833, lng: 5.5667, website: '#', shortDescription: 'Groot openluchtmuseum op de universiteitscampus.' },
  { id: 'be-07', name: 'Beeldenpark Zwijnaarde', location: 'Gent', region: 'België', lat: 51.0167, lng: 3.7167, website: '#', shortDescription: 'Modern park met diverse hedendaagse werken.' },
  { id: 'be-08', name: 'C-Mine Art Path', location: 'Genk', region: 'België', lat: 51.0000, lng: 5.5000, website: '#', shortDescription: 'Industriële kunst op een oude mijnsite.' },
  { id: 'be-09', name: 'Gaasbeek Castle Garden', location: 'Gaasbeek', region: 'België', lat: 50.7950, lng: 4.2050, website: '#', shortDescription: 'Beelden in een sprookjesachtige kasteeltuin.' },
  { id: 'be-10', name: 'Beaufort (Permanent)', location: 'Belgische Kust', region: 'België', lat: 51.2000, lng: 3.0000, website: '#', shortDescription: 'Permanente kunstroute langs de kustlijn.' },

  // --- FRANKRIJK & ITALIË (30+ locaties) ---
  { id: 'fr-01', name: 'Château La Coste', location: 'Provence', region: 'Frankrijk', lat: 43.6475, lng: 5.4950, website: '#', shortDescription: 'Mix van toparchitectuur en kunst.' },
  { id: 'fr-02', name: 'Maeght Foundation', location: 'Saint-Paul-de-Vence', region: 'Frankrijk', lat: 43.7008, lng: 7.1147, website: '#', shortDescription: 'Legendarische tuin met Miró.' },
  { id: 'fr-03', name: 'Musée de la Sculpture', location: 'Parijs', region: 'Frankrijk', lat: 48.8475, lng: 2.3614, website: '#', shortDescription: 'Beelden aan de Seine.' },
  { id: 'fr-04', name: 'Tuileries Garden', location: 'Parijs', region: 'Frankrijk', lat: 48.8633, lng: 2.3272, website: '#', shortDescription: 'Klassieke meesterwerken in het hart van Parijs.' },
  { id: 'fr-05', name: 'Kerguéhennec', location: 'Bretagne', region: 'Frankrijk', lat: 47.8833, lng: -2.7333, website: '#', shortDescription: 'Belangrijkste beeldenpark van Noord-Frankrijk.' },
  { id: 'fr-06', name: 'Villa Datris', location: 'L\'Isle-sur-la-Sorgue', region: 'Frankrijk', lat: 43.9167, lng: 5.0500, website: '#', shortDescription: 'Hedendaagse sculptuur in een Provençaals huis.' },
  { id: 'fr-07', name: 'Peyrassol', location: 'Flassans-sur-Issole', region: 'Frankrijk', lat: 43.3667, lng: 6.2167, website: '#', shortDescription: 'Wijn en monumentale kunst.' },
  { id: 'fr-08', name: 'Vassivière Island', location: 'Limousin', region: 'Frankrijk', lat: 45.8000, lng: 1.8667, website: '#', shortDescription: 'Land-art op een eiland.' },
  { id: 'fr-09', name: 'Palais-Royal Garden', location: 'Parijs', region: 'Frankrijk', lat: 48.8639, lng: 2.3372, website: '#', shortDescription: 'Buren kolommen en klassiek design.' },
  { id: 'fr-10', name: 'Giverny Monet Garden', location: 'Normandië', region: 'Frankrijk', lat: 49.0750, lng: 1.5333, website: '#', shortDescription: 'Levende schilderkunst en Japanse bruggen.' },
  { id: 'it-01', name: 'Arte Sella', location: 'Borgo Valsugana', region: 'Italië', lat: 46.0125, lng: 11.5238, website: '#', shortDescription: 'Natuur en kunst in de Alpen.' },
  { id: 'it-02', name: 'Giardino dei Tarocchi', location: 'Capalbio', region: 'Italië', lat: 42.4248, lng: 11.4667, website: '#', shortDescription: 'Kleurrijk park van Niki de Saint Phalle.' },
  { id: 'it-03', name: 'Chianti Park', location: 'Siena', region: 'Italië', lat: 43.3917, lng: 11.3917, website: '#', shortDescription: 'Hedendaags in Toscane.' },
  { id: 'it-04', name: 'Villa Panza', location: 'Varese', region: 'Italië', lat: 45.8286, lng: 8.8250, website: '#', shortDescription: 'Conceptuele kunst in een villa.' },
  { id: 'it-05', name: 'Il Giardino di Daniel Spoerri', location: 'Seggiano', region: 'Italië', lat: 42.9250, lng: 11.5583, website: '#', shortDescription: 'Surrealistische beeldentuin.' },
  { id: 'it-06', name: 'Peggy Guggenheim Garden', location: 'Venetië', region: 'Italië', lat: 45.4311, lng: 12.3314, website: '#', shortDescription: 'Beroemde beeldentuin aan het Canal Grande.' },
  { id: 'it-07', name: 'Bomarzo Monsters Park', location: 'Viterbo', region: 'Italië', lat: 42.4917, lng: 12.2475, website: '#', shortDescription: 'Historisch maniëristisch park met groteske beelden.' },
  { id: 'it-08', name: 'Fiumara d\'Arte', location: 'Sicilië', region: 'Italië', lat: 37.9333, lng: 14.3333, website: '#', shortDescription: 'Grootste openluchtmuseum van Europa aan zee.' },
  { id: 'it-09', name: 'La Suvera Park', location: 'Siena', region: 'Italië', lat: 43.3500, lng: 11.1667, website: '#', shortDescription: 'Beelden in de tuin van een pauselijke villa.' },
  { id: 'it-10', name: 'Sculpture Park of Siracusa', location: 'Sicilië', region: 'Italië', lat: 37.0750, lng: 15.2833, website: '#', shortDescription: 'Hedendaagse kunst in een klassieke omgeving.' },

  // --- UK & SCANDINAVIË & REST (20+ locaties) ---
  { id: 'uk-01', name: 'Yorkshire Sculpture Park', location: 'Wakefield', region: 'UK', lat: 53.6133, lng: -1.5667, website: '#', shortDescription: 'Grootste van het Verenigd Koninkrijk.' },
  { id: 'uk-02', name: 'Henry Moore Foundation', location: 'Perry Green', region: 'UK', lat: 51.8417, lng: 0.1167, website: '#', shortDescription: 'Landgoed van de meester.' },
  { id: 'uk-03', name: 'Jupiter Artland', location: 'Edinburgh', region: 'Schotland', lat: 55.9167, lng: -3.4167, website: '#', shortDescription: 'Sprookjesachtige Schotse tuin.' },
  { id: 'uk-04', name: 'Barbara Hepworth Garden', location: 'St Ives', region: 'UK', lat: 50.2133, lng: -5.4800, website: '#', shortDescription: 'Intieme tuin van de beeldhouwster.' },
  { id: 'uk-05', name: 'Cass Sculpture Foundation', location: 'Goodwood', region: 'UK', lat: 50.8667, lng: -0.7333, website: '#', shortDescription: 'Topstukken uit de Britse kunst.' },
  { id: 'scan-01', name: 'Kistefos', location: 'Noorwegen', region: 'Noorwegen', lat: 60.2227, lng: 10.3705, website: '#', shortDescription: 'Modern industrieel park.' },
  { id: 'scan-02', name: 'Vigeland', location: 'Oslo', region: 'Noorwegen', lat: 59.9270, lng: 10.7008, website: '#', shortDescription: 'Iconische bronzen figuren.' },
  { id: 'scan-03', name: 'Wanås Konst', location: 'Zweden', region: 'Zweden', lat: 56.1852, lng: 14.0444, website: '#', shortDescription: 'Kunst in een sprookjesbos.' },
  { id: 'scan-04', name: 'Skovsnogen', location: 'Denemarken', region: 'Denemarken', lat: 55.9193, lng: 8.9074, website: '#', shortDescription: 'Experimentele boskunst.' },
  { id: 'scan-05', name: 'Louisiana Museum Garden', location: 'Humlebæk', region: 'Denemarken', lat: 55.9680, lng: 12.5430, website: '#', shortDescription: 'Beelden met uitzicht op de Sont.' },
  { id: 'at-01', name: 'Austrian Sculpture Park', location: 'Graz', region: 'Oostenrijk', lat: 46.9614, lng: 15.4856, website: '#', shortDescription: 'Zeven hectare moderne kunst.' },
  { id: 'ch-01', name: 'Gianadda Foundation', location: 'Martigny', region: 'Zwitserland', lat: 46.0945, lng: 7.0706, website: '#', shortDescription: 'Meesterwerken in de bergen.' },
  { id: 'pt-01', name: 'Serralves Foundation', location: 'Porto', region: 'Portugal', lat: 41.1583, lng: -8.6583, website: '#', shortDescription: 'Art Deco tuin met monumentale kunst.' },
  { id: 'pt-02', name: 'Quinta dos Carvalhais', location: 'Dão', region: 'Portugal', lat: 40.5000, lng: -7.9000, website: '#', shortDescription: 'Beelden tussen de wijngaarden.' },
  { id: 'pt-03', name: 'Buddha Eden Garden', location: 'Bombarral', region: 'Portugal', lat: 39.2333, lng: -9.1333, website: '#', shortDescription: 'Grootste oosterse tuin van Europa.' },
  { id: 'hu-01', name: 'Memento Park', location: 'Boedapest', region: 'Hongarije', lat: 47.4267, lng: 19.0000, website: '#', shortDescription: 'Monumentale communistische beelden.' },
  { id: 'cz-01', name: 'Lidice Memorial Garden', location: 'Lidice', region: 'Tsjechië', lat: 50.1433, lng: 14.1900, website: '#', shortDescription: 'Ontroerend gedenkteken met beeldengroep.' },
  { id: 'pl-01', name: 'Orońsko Sculpture Centre', location: 'Orońsko', region: 'Polen', lat: 51.3167, lng: 20.9833, website: '#', shortDescription: 'Het nationale centrum voor Poolse beeldhouwkunst.' },
  { id: 'ie-01', name: 'Victor\'s Way', location: 'Wicklow', region: 'Ierland', lat: 53.0333, lng: -6.2167, website: '#', shortDescription: 'Meditatief beeldenpark.' },
  { id: 'gr-01', name: 'Olympic Stadium Park', location: 'Athene', region: 'Griekenland', lat: 38.0361, lng: 23.7847, website: '#', shortDescription: 'Moderne Griekse monumenten.' }
];
